name: Matrix

on:
  workflow_dispatch:

jobs:
  build:
    name: Publish ${{ matrix.os }} / py${{ matrix.python }} / ${{ matrix.variant }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        python: [38, 39]
        include:
          - os: ubuntu-24.04
            variant: manylinux
          - os: ubuntu-24.04
            variant: musllinux
          - os: ubuntu-24.04-arm
            variant: manylinux
          - os: ubuntu-24.04-arm
            variant: musllinux
          - os: macos-15
    
    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        run: echo "${CIBW_BUILD} ${{ matrix.os }} / py${{ matrix.python }} / ${{ matrix.variant }}"
        env:
          CIBW_BUILD: cp${{ matrix.python }}-*
