name: Matrix

on:
  workflow_dispatch:

jobs:
  build:
    name: Publish ${{ matrix.os }} / py${{ matrix.python }} / ${{ matrix.variant }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-15]
        variant: [manylinux, musllinux]
        python: [38, 39]
        exclude:
          - os: macos-15
            variant: musllinux
    
    steps:
      - uses: actions/checkout@v4

      - name: Configuration
        id: configuration
        run: |
          if [ "${{ matrix.os }}" != "macos-15" ]; then
            BUILD_VARIANT="cp${{ matrix.python }}-${{ matrix.variant }}_*"
          else
            BUILD_VARIANT="cp${{ matrix.python }}-*"
          fi
          echo "build_variant=$BUILD_VARIANT" >> $GITHUB_OUTPUT

      - name: Build wheels
        run: echo "${CIBW_BUILD}"
        env:
          CIBW_BUILD: ${{ steps.configuration.outputs.build_variant }}
