name: Matrix

on:
  workflow_dispatch:

jobs:
  build:
    name: Publish ${{ matrix.os }} / py${{ matrix.python }} / ${{ matrix.variant }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-15]
        variant: [manylinux, musllinux]
        python: [38, 39]
        exclude:
          - os: macos-15
            variant: musllinux
    
    steps:
      - uses: actions/checkout@v4

      - name: Configuration
        id: configuration
        run: |
          # The build setting for cibuildwheel
          if [ "${{ matrix.os }}" != "macos-15" ]; then
            BUILD_VARIANT="cp${{ matrix.python }}-${{ matrix.variant }}_*"
          else
            BUILD_VARIANT="cp${{ matrix.python }}-*"
          fi
          echo "build_variant=$BUILD_VARIANT" >> $GITHUB_OUTPUT
          
          # The script to run to install dependencies in the platform-specific cibuildwheel container
          if [ "${{ matrix.os }}" == "ubuntu-24.04-arm" ]; then
            if [ "${{ matrix.variant }}" == "manylinux" ]; then
              BEFORE_BUILD="yum install -y clang clang-tools-extra"
            else
              BEFORE_BUILD="apk add clang clang-extra-tools"
            fi
          else
            BEFORE_BUILD=""
          fi
          echo "before_build=$BEFORE_BUILD" >> $GITHUB_OUTPUT

          # The package version
          VERSION=(grep '^version *= *' pyproject.toml | sed -E 's/version *= *"(.*)"/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Build wheels
        run: echo "${{ steps.configuration.outputs.version }}"
        env:
          CIBW_BUILD: ${{ steps.configuration.outputs.build_variant }}
          CIBW_ENVIRONMENT: 'CXX="clang++" CC="clang"'
          CIBW_BEFORE_BUILD: ${{ steps.configuration.outputs.before_build }}
