name: Matrix

on:
  workflow_dispatch:

jobs:
  build:
    name: Publish ${{ matrix.os }} / py${{ matrix.python }} / ${{ matrix.variant }}

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-15]
        variant: [manylinux, musllinux]
        python: [38, 39]
    
    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        run: echo "${CIBW_BUILD} ${{ matrix.os }} / py${{ matrix.python }} / ${{ matrix.variant }}"
        env:
          CIBW_BUILD: cp${{ matrix.python }}-*
